name: Build latest

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Build"
    steps:
      - uses: actions/checkout@v1

      - name: Build base image
        run: docker build --no-cache -t enhavo/enhavo-app:base images/base

      - name: Build 7.2-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:7.2-fpm-latest images/7.2-fpm

      - name: Build 7.2-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:7.2-nginx-latest images/7.2-nginx

      - name: Build 7.2-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:7.2-apache-latest images/7.2-apache

      - name: Build 7.3-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:7.3-fpm-latest images/7.3-fpm

      - name: Build 7.3-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:7.3-nginx-latest images/7.3-nginx

      - name: Build 7.3-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:7.3-apache-latest images/7.3-apache

      - name: Build 7.4-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-fpm-latest images/7.4-fpm

      - name: Build 7.4-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-nginx-latest images/7.4-nginx

      - name: Build 7.4-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-apache-latest images/7.4-apache

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Push 7.2-nginx image
        run: docker push enhavo/enhavo-app:7.2-nginx-latest

      - name: Push 7.2-fpm image
        run: docker push enhavo/enhavo-app:7.2-fpm-latest

      - name: Push 7.2-apache image
        run: docker push enhavo/enhavo-app:7.2-apache-latest

      - name: Push 7.3-nginx image
        run: docker push enhavo/enhavo-app:7.3-nginx-latest

      - name: Push 7.3-apache image
        run: docker push enhavo/enhavo-app:7.3-apache-latest

      - name: Push 7.3-fpm image
        run: docker push enhavo/enhavo-app:7.3-fpm-latest

      - name: Push 7.4-nginx image
        run: docker push enhavo/enhavo-app:7.4-nginx-latest

      - name: Push 7.4-apache image
        run: docker push enhavo/enhavo-app:7.4-apache-latest

      - name: Push 7.4-fpm image
        run: docker push enhavo/enhavo-app:7.4-fpm-latest
