name: Build release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build all and push"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set env version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')" >> $GITHUB_ENV

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all
        run: make build-all

      - name: Push all
        run: VERSION=${{ env.VERSION }} make push-all
