name: Build release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Build"
    steps:
      - uses: actions/checkout@v1

      - name: Build base image
        run: docker build --no-cache -t enhavo/enhavo-app:base images/base

      - name: Build 7.4-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-fpm-latest images/7.4-fpm

      - name: Build 7.4-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-nginx-latest images/7.4-nginx

      - name: Build 7.4-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:7.4-apache-latest images/7.4-apache

      - name: Build 8.0-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:8.0-fpm-latest images/8.0-fpm

      - name: Build 8.0-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:8.0-nginx-latest images/8.0-nginx

      - name: Build 8.0-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:8.0-apache-latest images/8.0-apache

      - name: Build 8.1-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:8.1-fpm-latest images/8.1-fpm

      - name: Build 8.1-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:8.1-nginx-latest images/8.1-nginx

      - name: Build 8.1-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:8.1-apache-latest images/8.1-apache

      - name: Build 8.2-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:8.2-fpm-latest images/8.2-fpm

      - name: Build 8.2-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:8.2-nginx-latest images/8.2-nginx

      - name: Build 8.2-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:8.2-apache-latest images/8.2-apache

      - name: Build 8.3-fpm image
        run: docker build --no-cache -t enhavo/enhavo-app:8.3-fpm-latest images/8.3-fpm

      - name: Build 8.3-nginx image
        run: docker build --no-cache -t enhavo/enhavo-app:8.3-nginx-latest images/8.3-nginx

      - name: Build 8.3-apache image
        run: docker build --no-cache -t enhavo/enhavo-app:8.3-apache-latest images/8.3-apache

      - name: Set env version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/v//g')" >> $GITHUB_ENV

      - name: Tag images
        run: |
          docker tag enhavo/enhavo-app:7.4-nginx-latest "enhavo/enhavo-app:7.4-nginx-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:7.4-apache-latest "enhavo/enhavo-app:7.4-apache-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:7.4-fpm-latest "enhavo/enhavo-app:7.4-fpm-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.0-nginx-latest "enhavo/enhavo-app:8.0-nginx-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.0-apache-latest "enhavo/enhavo-app:8.0-apache-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.0-fpm-latest "enhavo/enhavo-app:8.0-fpm-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.1-nginx-latest "enhavo/enhavo-app:8.1-nginx-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.1-apache-latest "enhavo/enhavo-app:8.1-apache-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.1-fpm-latest "enhavo/enhavo-app:8.1-fpm-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.2-nginx-latest "enhavo/enhavo-app:8.2-nginx-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.2-apache-latest "enhavo/enhavo-app:8.2-apache-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.2-fpm-latest "enhavo/enhavo-app:8.2-fpm-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.3-nginx-latest "enhavo/enhavo-app:8.3-nginx-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.3-apache-latest "enhavo/enhavo-app:8.3-apache-${{ env.VERSION }}"
          docker tag enhavo/enhavo-app:8.3-fpm-latest "enhavo/enhavo-app:8.3-fpm-${{ env.VERSION }}"
      - name: Show images
        run: docker images

      - name: Show Version
        run: echo ${{ env.VERSION }}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Push 7.4-nginx image
        run: docker push enhavo/enhavo-app:7.4-nginx-${{ env.VERSION }}

      - name: Push 7.4-apache image
        run: docker push enhavo/enhavo-app:7.4-apache-${{ env.VERSION }}

      - name: Push 7.4-fpm image
        run: docker push enhavo/enhavo-app:7.4-fpm-${{ env.VERSION }}

      - name: Push 8.0-nginx image
        run: docker push enhavo/enhavo-app:8.0-nginx-${{ env.VERSION }}

      - name: Push 8.0-apache image
        run: docker push enhavo/enhavo-app:8.0-apache-${{ env.VERSION }}

      - name: Push 8.0-fpm image
        run: docker push enhavo/enhavo-app:8.0-fpm-${{ env.VERSION }}

      - name: Push 8.1-nginx image
        run: docker push enhavo/enhavo-app:8.1-nginx-${{ env.VERSION }}

      - name: Push 8.1-apache image
        run: docker push enhavo/enhavo-app:8.1-apache-${{ env.VERSION }}

      - name: Push 8.1-fpm image
        run: docker push enhavo/enhavo-app:8.1-fpm-${{ env.VERSION }}

      - name: Push 8.2-nginx image
        run: docker push enhavo/enhavo-app:8.2-nginx-${{ env.VERSION }}

      - name: Push 8.2-apache image
        run: docker push enhavo/enhavo-app:8.2-apache-${{ env.VERSION }}

      - name: Push 8.2-fpm image
        run: docker push enhavo/enhavo-app:8.2-fpm-${{ env.VERSION }}
        
      - name: Push 8.3-nginx image
        run: docker push enhavo/enhavo-app:8.3-nginx-${{ env.VERSION }}

      - name: Push 8.3-apache image
        run: docker push enhavo/enhavo-app:8.3-apache-${{ env.VERSION }}

      - name: Push 8.3-fpm image
        run: docker push enhavo/enhavo-app:8.3-fpm-${{ env.VERSION }}
